import type { GuidanceConcept, GuidanceCondition, GuidanceSource, LocalizedText } from "./model";

const text = (en: string, es: string): LocalizedText => ({ en, es });
const condition = (key: GuidanceCondition["key"], en: string, es: string, equals?: string | boolean): GuidanceCondition => ({ key, label: text(en, es), ...(equals === undefined ? {} : { equals }) });
const source = (id: string, agency: string, citation: string, url: string, supports: string): GuidanceSource => ({ id, agency, citation, url, supports, lastVerified: "2026-09-03", sourceVersion: "public-guidance-2026-09-03" });

export const PR_GUIDANCE_SOURCES = {
  alcohol: source("SRC_GUIDANCE_ALCOHOL", "Departamento de Hacienda", "Internal Revenue Code, Subtitle E; licensing FAQs", "https://hacienda.pr.gov/sites/default/files/codigo_de_rentas_internas.pdf", "Subtitle E, sections 5050.01–5050.18: licensing alcoholic-beverage dealers and limits on licensed sales."),
  ein: source("SRC_GUIDANCE_EIN", "Internal Revenue Service", "Employer identification number — who needs an EIN; confirmation", "https://www.irs.gov/businesses/employer-identification-number", "Employers need an EIN; IRS confirmation documents the assigned number; form the legal entity before applying."),
  merchant: source("SRC_GUIDANCE_MERCHANT", "Departamento de Hacienda", "SURI — merchant location registration and certificates", "https://hacienda.pr.gov/transacciones-que-puedes-realizar-traves-de-suri", "SURI registers merchant locations and issues the Merchant Registration Certificate electronically."),
  merchantLaw: source("SRC_GUIDANCE_MERCHANT_RULE", "Departamento de Hacienda", "Regulation 8942 — Merchant Registration Certificate", "https://hacienda.pr.gov/sites/default/files/8942.pdf", "Merchant registration identifies each commercial location and whether the merchant is an IVU withholding agent."),
  permiso: source("SRC_GUIDANCE_PU", "OGPe", "Nonresidential use — permits for a business or activity", "https://www.permisos.pr.gov/", "Nonresidential uses require the Permiso Único process; check permitted use and applicable special licenses in SBP."),
  bayamon: source("SRC_GUIDANCE_PATENTE_BAYAMON", "Municipio de Bayamón", "Patente Municipal — commercial activity and provisional filing", "https://www.municipiodebayamon.com/servicios-municipales/empresas/patente-municipal/", "Municipal patent is a tax on volume of business; Bayamón provides provisional and volume-of-business filings."),
  lease: source("SRC_GUIDANCE_LEASE_BAYAMON", "Municipio de Bayamón", "Permiso Único — property evidence checklist", "https://www.municipiodebayamon.com/servicios-municipales/oficina-de-permisos/permiso-unico-pu/", "The municipal PU checklist accepts a property deed or lease as supporting evidence."),
  entity: source("SRC_GUIDANCE_ENTITY", "Departamento de Estado", "Corporations — LLC formation by Certificate of Organization", "https://www.estado.pr.gov/corporaciones", "An LLC is created through a Certificate of Organization; corporations use the incorporation process."),
  cfse: source("SRC_GUIDANCE_CFSE", "Corporación del Fondo del Seguro del Estado", "Employer information — workers compensation coverage", "https://old.fondopr.com/patronos/informacion-general/", "Employers hire compensated workers; insured employers formalize a CFSE policy, report payroll, risks and locations, and pay premiums."),
  zoning: source("SRC_GUIDANCE_ZONING", "OGPe", "Single Business Portal — land use / zoning consultation", "https://www.permisos.pr.gov/", "SBP's location consultation confirms the permitted use classification for the premises before a use permit is issued."),
  municipalReg: source("SRC_GUIDANCE_MUNICIPAL_REG", "Municipio de Bayamón", "Hacienda Municipal — business registration services", "https://www.municipiodebayamon.com/servicios-municipales/empresas/", "Bayamón's municipal Hacienda office registers commercial businesses operating within the municipality, separate from state SURI registration."),
  municipalTax: source("SRC_GUIDANCE_MUNICIPAL_TAX", "Municipio de Bayamón", "Hacienda Municipal — patente and tax compliance certification", "https://www.municipiodebayamon.com/servicios-municipales/empresas/patente-municipal/", "The municipal Hacienda office issues tax-compliance certification once patente filings and payments are current."),
  health: source("SRC_GUIDANCE_HEALTH", "Departamento de Salud", "Reglamento General de Salud Ambiental — sanitary permit for establishments", "https://www.salud.pr.gov/", "Establishments handling food or serving the public are subject to sanitary-permit inspection under environmental health regulation."),
  fire: source("SRC_GUIDANCE_FIRE", "Cuerpo de Bomberos de Puerto Rico", "Fire inspection certificate for commercial occupancy", "https://bomberos.pr.gov/", "Commercial premises open to the public or handling food/manufacturing require a fire-safety inspection certificate before occupancy."),
  cfpm: source("SRC_GUIDANCE_CFPM", "Departamento de Salud", "Manejador de Alimentos — certified food handler/manager requirement", "https://www.salud.pr.gov/", "Establishments that prepare food must have a certified food protection manager or handler on staff per sanitary regulation."),
  stormwater: source("SRC_GUIDANCE_STORMWATER", "EPA / Junta de Calidad Ambiental", "NPDES MS4 stormwater program", "https://www.epa.gov/npdes/npdes-stormwater-program", "Municipalities covered by an MS4 permit require regulated businesses to control runoff from their site under the NPDES stormwater program."),
  noise: source("SRC_GUIDANCE_NOISE", "Junta de Calidad Ambiental", "Reglamento de Control de Ruido — endorsement for elevated noise activity", "https://jca.pr.gov/", "Activities that generate elevated noise levels in designated municipal zones need a noise-control endorsement before operating."),
  waste: source("SRC_GUIDANCE_WASTE", "Autoridad de Desperdicios Sólidos", "Commercial solid waste collection and disposal", "https://www.ads.pr.gov/", "Commercial generators of solid waste must contract collection and disposal service rather than use residential collection."),
  parking: source("SRC_GUIDANCE_PARKING", "OGPe", "Single Business Portal — off-street parking requirement review", "https://www.permisos.pr.gov/", "The use-permit review confirms the premises provide the off-street parking required for the proposed commercial activity."),
  luma: source("SRC_GUIDANCE_LUMA", "Negociado de Energía de Puerto Rico", "Reglamento 8915 — interconexión de generadores con el sistema de distribución", "https://energia.pr.gov/wp-content/uploads/sites/7/2024/04/20240419-MI20190009-Mocion-en-Cumplimiento-de-Orden-Emitida-el-15-de-abril-de-2024.pdf", "The Negociado de Energía oversees the interconnection regulation for distributed generators connecting to the distribution system (Reglamento 8915)."),
  netMetering: source("SRC_GUIDANCE_NET_METERING", "Negociado de Energía de Puerto Rico", "Resolución sobre medición neta y energía distribuida", "https://energia.pr.gov/wp-content/uploads/sites/7/2024/06/20240614-MI20240006-Resolucion.pdf", "The Negociado de Energía regulates the net metering program and distributed energy under Ley 114-2007, as amended."),
  solarOgpe: source("SRC_GUIDANCE_SOLAR_OGPE", "OGPe", "Single Business Portal — construction and use permits", "https://www.permisos.pr.gov/", "Construction and use permits for energy projects are processed through OGPe's Single Business Portal; rooftop photovoltaic systems of 1 MW or less on existing structures are exempt from OGPe construction and use permits."),
};

const employee = condition("Q_EMPLOYEES_HIRED", "Hiring employees", "Contratación de empleados", true);
const municipality = condition("municipality", "Municipality", "Municipio");
const business = condition("businessType", "Commercial activity", "Actividad comercial");
const SUBJECTS: Record<string, { en: string[]; es: string[] }> = {
  DOC_ALCOHOL_LICENSE: { en: ["alcohol"], es: ["alcohol", "alcohólic"] },
  DOC_EIN: { en: ["ein", "federal tax identifier"], es: ["ein", "identificador contributivo"] },
  DOC_MERCHANT_REGISTRATION: { en: ["merchant", "suri", "ivu"], es: ["comerciante", "suri", "ivu"] },
  DOC_PERMISO_UNICO: { en: ["permit"], es: ["permiso", "solicitud en sbp"] },
  DOC_PATENTE_MUNICIPAL: { en: ["patent", "municipal tax"], es: ["patente", "contributivo municipal"] },
  DOC_LEASE_AGREEMENT: { en: ["lease", "landlord"], es: ["contrato", "arrendador"] },
  DOC_ARTICLES_ORGANIZATION: { en: ["llc", "limited liability company", "organization"], es: ["llc", "compañía de responsabilidad limitada", "organización"] },
  DOC_WORKERS_COMP: { en: ["cfse", "coverage"], es: ["cfse", "cobertura"] },
  DOC_ZONING: { en: ["zoning", "use classification"], es: ["zonificación", "clasificación de uso"] },
  DOC_MUNICIPAL_REGISTRATION: { en: ["municipal", "registration"], es: ["municipal", "registro"] },
  DOC_MUNICIPAL_TAX_COMPLIANCE: { en: ["municipal", "tax compliance"], es: ["municipal", "cumplimiento contributivo"] },
  DOC_HEALTH_PERMIT: { en: ["sanitary", "health"], es: ["sanitario", "salud"] },
  DOC_FIRE_CERT: { en: ["fire", "inspection"], es: ["bomberos", "inspección"] },
  DOC_CFPM: { en: ["food protection manager", "food handler"], es: ["manejador de alimentos"] },
  DOC_STORMWATER_PLAN: { en: ["stormwater", "runoff"], es: ["escorrentía", "pluvial"] },
  DOC_NOISE_VARIANCE: { en: ["noise"], es: ["ruido"] },
  DOC_WASTE_COLLECTION_CONTRACT: { en: ["waste", "collection"], es: ["desperdicios", "recolección"] },
  DOC_PARKING_COMPLIANCE: { en: ["parking"], es: ["estacionamiento"] },
  DOC_LUMA_INTERCONNECTION: { en: ["luma", "interconnection", "grid connection"], es: ["luma", "interconexión", "conexión"] },
  DOC_NET_METERING_AGREEMENT: { en: ["net metering", "export"], es: ["medición neta", "exportar"] },
  DOC_OGPE_CONSTRUCTION_PERMIT: { en: ["ogpe", "construction permit"], es: ["ogpe", "permiso de construcción"] },
  DOC_OWNER_AFFIDAVIT: { en: ["affidavit", "owner authorization"], es: ["declaración jurada", "autorización del dueño"] },
  DOC_OPPE_INSTALLER_REG: { en: ["oppe", "installer registration"], es: ["oppe", "registro de instalador"] },
};
function concept(requirementId: string, conditions: GuidanceCondition[][], sources: GuidanceSource[], content: [LocalizedText, LocalizedText, LocalizedText, LocalizedText], dependencies: string[] = []): GuidanceConcept {
  return { requirementId, version: "2026-09-03.1", validationStatus: "validated", subjectTerms: SUBJECTS[requirementId], conditions, sources, regulatoryReason: content[0], purpose: content[1], nextAction: content[2], consequenceOrNextStep: content[3], dependencies,
    ...(requirementId === "DOC_EIN" ? { conditionalDependencies: [
      { entityType: "limited_liability_company", documentId: "DOC_ARTICLES_ORGANIZATION" },
      ...["stock_corporation", "close_corporation", "professional_corporation", "nonprofit_nonstock_corporation"].map(entityType => ({ entityType, documentId: "DOC_CERT_INCORPORATION" })),
    ] } : {}),
  };
}

// These are reusable concepts ON the document nodes, not an alternate matcher.
// No fees, deadlines or inferred customer facts. Local sources stay local.
export const PR_REQUIREMENT_GUIDANCE: Record<string, GuidanceConcept> = {
  DOC_ALCOHOL_LICENSE: concept("DOC_ALCOHOL_LICENSE", [[condition("Q_ALCOHOL_SOLD", "Alcohol sales: Yes", "Venta de alcohol: Sí", true)]], [PR_GUIDANCE_SOURCES.alcohol], [
    text("Selling alcoholic beverages is separately licensed. Ordinary business registration does not itself authorize alcohol sales.", "La venta de bebidas alcohólicas requiere una licencia específica. El registro del negocio por sí solo no autoriza esas ventas."),
    text("The Hacienda license authorizes the category of alcoholic-beverage sales specified in it.", "La licencia de Hacienda autoriza la categoría de venta de bebidas alcohólicas que especifica."),
    text("Confirm the sales category, complete the alcohol-license application, and supply the supporting evidence requested for that category.", "Confirma la categoría de venta, completa la solicitud de licencia de alcohol y aporta la evidencia de respaldo correspondiente."),
    text("Issuance authorizes only the alcohol sales covered by that license, subject to its conditions; a prepared application is not authorization.", "La expedición autoriza solo las ventas de alcohol cubiertas por la licencia y sus condiciones; una solicitud preparada no es una autorización."),
  ]),
  DOC_EIN: concept("DOC_EIN", [[employee]], [PR_GUIDANCE_SOURCES.ein], [
    text("Employers need a federal tax identifier for employment-tax reporting. The EIN identifies the business to the IRS.", "Los patronos necesitan un identificador contributivo federal para informar contribuciones sobre el empleo. El EIN identifica al negocio ante el IRS."),
    text("IRS confirmation is official evidence of the EIN assigned to the business, not the application for that number.", "La confirmación del IRS es evidencia oficial del EIN asignado al negocio, no la solicitud de ese número."),
    text("Prepare the EIN application, or upload IRS confirmation if already assigned. Form a new legal entity before applying.", "Prepara la solicitud del EIN o sube la confirmación del IRS si ya fue asignado. Constituye la entidad antes de solicitarlo."),
    text("The assigned EIN can identify the business on tax returns and later licensing applications. Do not substitute a draft for IRS confirmation.", "El EIN asignado identifica al negocio en planillas y solicitudes de licencias. Un borrador no sustituye la confirmación del IRS."),
  ]),
  DOC_MERCHANT_REGISTRATION: concept("DOC_MERCHANT_REGISTRATION", [[business]], [PR_GUIDANCE_SOURCES.merchant, PR_GUIDANCE_SOURCES.merchantLaw], [
    text("Puerto Rico's merchant-registration process identifies commercial locations and their sales-tax treatment with Hacienda.", "El registro de comerciantes de Puerto Rico identifica los locales comerciales y su tratamiento del IVU ante Hacienda."),
    text("The certificate records the merchant's location and whether it is an IVU withholding agent; it is not a business-use permit.", "El certificado identifica la localidad del comerciante y si es agente retenedor del IVU; no es un permiso de uso."),
    text("Review business, tax and location details for registration in SURI. Upload the issued Merchant Registration Certificate when available.", "Revisa los datos del negocio, contributivos y de localidad para registrarte en SURI. Sube el Certificado de Registro de Comerciante emitido."),
    text("The issued certificate documents the merchant registration for later filings; it does not replace location or activity-specific permits.", "El certificado emitido acredita el registro de comerciante en trámites posteriores; no sustituye permisos de uso ni licencias específicas."),
  ]),
  DOC_PERMISO_UNICO: concept("DOC_PERMISO_UNICO", [[condition("Q_PHYSICAL_LOCATION", "Nonresidential business location", "Local comercial no residencial", true)]], [PR_GUIDANCE_SOURCES.permiso], [
    text("Nonresidential business use requires the Permiso Único process, including review of permitted use and applicable operating licenses.", "El uso comercial no residencial requiere el trámite de Permiso Único y revisar el uso permitido y las licencias aplicables."),
    text("This is the operating-permit process for the proposed activity at the premises, not entity formation.", "Es el trámite de permiso para la actividad propuesta en el local, no la constitución de la entidad."),
    text("Check permitted use, assemble the property evidence and applicable license information, and complete the permit application in SBP.", "Verifica el uso permitido, reúne la evidencia de la propiedad y las licencias aplicables, y completa la solicitud en SBP."),
    text("An issued permit covers the approved use at that location, subject to its terms. Preparing the package does not authorize operation.", "El permiso emitido cubre el uso aprobado en esa ubicación y sus condiciones. Preparar el paquete no autoriza operar."),
  ]),
  DOC_PATENTE_MUNICIPAL: concept("DOC_PATENTE_MUNICIPAL", [[{ ...municipality, equals: "Bayamón" }, business]], [PR_GUIDANCE_SOURCES.bayamon], [
    text("Bayamón's municipal patent taxes the volume of business from commercial activity, subject to applicable exceptions.", "La patente de Bayamón grava el volumen de negocios de la actividad comercial, sujeto a las excepciones aplicables."),
    text("The patent is a municipal business-tax obligation, separate from permission to use the premises.", "La patente es una obligación contributiva municipal, distinta del permiso para usar el local."),
    text("For a new business, prepare Bayamón's provisional patent filing; an existing operation should review the volume-of-business filing instead.", "Para un negocio nuevo, prepara la solicitud de patente provisional de Bayamón; una operación existente debe revisar la declaración de volumen de negocios."),
    text("The filing establishes the municipal tax record used for subsequent volume-of-business reporting and patent payments.", "La radicación establece el expediente contributivo municipal para futuras declaraciones de volumen de negocios y pagos de patente."),
  ]),
  DOC_LEASE_AGREEMENT: concept("DOC_LEASE_AGREEMENT", [[condition("Q_EXISTING_LEASE", "Leased premises confirmed", "Local arrendado confirmado", true), { ...municipality, equals: "Bayamón" }]], [PR_GUIDANCE_SOURCES.lease], [
    text("Bayamón's permit checklist requests a lease or deed as property evidence. A lease documents the business's right to occupy rented premises.", "El listado de permisos de Bayamón solicita contrato de arrendamiento o escritura. El contrato documenta el derecho a ocupar el local arrendado."),
    text("This is the agreement with the landlord, not a government-issued permit or proof that the proposed use is approved.", "Es el acuerdo con el arrendador, no un permiso gubernamental ni prueba de que el uso propuesto esté aprobado."),
    text("Upload the signed lease and check that the tenant and premises match the permit application.", "Sube el contrato firmado y verifica que el arrendatario y el local coincidan con la solicitud del permiso."),
    text("The lease supports the property's occupancy evidence in the permit package; the authority must still approve the proposed use.", "El contrato respalda la evidencia de ocupación del inmueble; la autoridad todavía debe aprobar el uso propuesto."),
  ]),
  DOC_ARTICLES_ORGANIZATION: concept("DOC_ARTICLES_ORGANIZATION", [[condition("entityType", "Entity: Puerto Rico LLC", "Entidad: LLC de Puerto Rico", "limited_liability_company")]], [PR_GUIDANCE_SOURCES.entity], [
    text("Selecting an LLC structure does not create the company. Puerto Rico forms an LLC through a Certificate of Organization.", "Elegir la estructura LLC no crea la compañía. Puerto Rico constituye una LLC mediante un Certificado de Organización."),
    text("The formation document establishes the limited liability company with the Department of State.", "El documento de constitución establece la compañía de responsabilidad limitada ante el Departamento de Estado."),
    text("Complete the Certificate of Organization with the company, address and resident-agent details. If already formed, provide the existing formation evidence.", "Completa el Certificado de Organización con los datos de compañía, dirección y agente residente. Si ya está constituida, aporta la evidencia existente."),
    text("After formation is accepted, use the LLC's legal identity for EIN, tax and licensing applications; a completed draft is not formation.", "Tras aceptarse la constitución, usa la identidad legal de la LLC en solicitudes de EIN, contribuciones y licencias; un borrador no constituye la entidad."),
  ]),
  DOC_WORKERS_COMP: concept("DOC_WORKERS_COMP", [[employee]], [PR_GUIDANCE_SOURCES.cfse], [
    text("Hiring workers creates employer responsibilities for workplace-injury coverage through CFSE, subject to the applicable coverage rules.", "Contratar trabajadores conlleva responsabilidades patronales de cobertura por lesiones ocupacionales mediante la CFSE, según las reglas aplicables."),
    text("The CFSE policy documents workers' compensation coverage for the reported workforce, risks and locations.", "La póliza de la CFSE documenta cobertura por accidentes del trabajo para la plantilla, riesgos y localidades informados."),
    text("Provide payroll, work-risk and location information for the CFSE policy process; upload issued coverage evidence when available.", "Aporta nómina, riesgos laborales y localidades para el trámite de póliza de la CFSE; sube la evidencia de cobertura emitida."),
    text("Issued coverage supports employer readiness. Payroll reporting and premium obligations continue; an application alone is not insurance.", "La cobertura emitida respalda la preparación patronal. Continúan las obligaciones de nómina y primas; una solicitud sola no es un seguro."),
  ]),
  DOC_ZONING: concept("DOC_ZONING", [[condition("Q_PHYSICAL_LOCATION", "Nonresidential business location", "Local comercial no residencial", true)]], [PR_GUIDANCE_SOURCES.zoning], [
    text("A physical commercial premises must be confirmed for the proposed activity's use classification before other permits build on it.", "Un local comercial físico requiere confirmar la clasificación de uso de la actividad propuesta antes de tramitar otros permisos sobre esa base."),
    text("Zoning / use certification confirms the premises' permitted use classification for the proposed activity, not the activity's other licenses.", "La certificación de zonificación confirma la clasificación de uso permitido del local para la actividad propuesta; no cubre otras licencias de la actividad."),
    text("Request the zoning / use classification consultation in SBP for the premises and confirm it matches the proposed activity.", "Solicita la consulta de zonificación y clasificación de uso en SBP para el local y confirma que coincide con la actividad propuesta."),
    text("A confirmed use classification supports the Permiso Único application for that location; it does not by itself authorize operation.", "La clasificación de uso confirmada respalda la solicitud de Permiso Único para ese local; por sí sola no autoriza operar."),
  ]),
  DOC_MUNICIPAL_REGISTRATION: concept("DOC_MUNICIPAL_REGISTRATION", [[business]], [PR_GUIDANCE_SOURCES.municipalReg], [
    text("Municipalities register commercial businesses operating within their territory, separately from state-level merchant registration.", "Los municipios registran los negocios comerciales que operan en su territorio, de forma independiente al registro de comerciante estatal."),
    text("Municipal registration identifies the business to the municipal Hacienda office for local tax and licensing purposes.", "El registro municipal identifica al negocio ante la Hacienda Municipal para fines contributivos y de licenciamiento locales."),
    text("Complete the municipal business-registration application with the business and location details for the municipal Hacienda office.", "Completa la solicitud de registro municipal con los datos del negocio y del local para la Hacienda Municipal."),
    text("The municipal registration record is the basis for subsequent patente filings and municipal tax-compliance certification.", "El registro municipal es la base para las declaraciones de patente y la certificación de cumplimiento contributivo municipal posteriores."),
  ]),
  DOC_MUNICIPAL_TAX_COMPLIANCE: concept("DOC_MUNICIPAL_TAX_COMPLIANCE", [[business]], [PR_GUIDANCE_SOURCES.municipalTax], [
    text("Municipal Hacienda offices certify that a business's patente and other municipal tax obligations are current before certain filings proceed.", "La Hacienda Municipal certifica que las obligaciones de patente y otras contribuciones municipales del negocio están al día antes de ciertos trámites."),
    text("The tax-compliance certificate documents that municipal filings and payments are current; it does not itself set the patente rate.", "El certificado de cumplimiento acredita que las declaraciones y pagos municipales están al día; no establece la tasa de la patente."),
    text("File any outstanding patente returns and settle balances, then request the municipal tax-compliance certificate from Hacienda Municipal.", "Radica las declaraciones de patente pendientes y salda los balances; luego solicita el certificado de cumplimiento a la Hacienda Municipal."),
    text("The issued certificate documents good standing with the municipality at the time it was issued; new filings can affect that status later.", "El certificado emitido acredita el cumplimiento contributivo municipal al momento de expedirse; nuevas declaraciones pueden afectar ese estatus después."),
  ]),
  DOC_HEALTH_PERMIT: concept("DOC_HEALTH_PERMIT", [[condition("Q_FOOD_PREPARED", "Food prepared on site", "Alimentos preparados en el local", true)], [condition("Q_FOOD_SOLD", "Food sold on site", "Alimentos vendidos en el local", true)]], [PR_GUIDANCE_SOURCES.health], [
    text("Establishments that prepare or sell food are subject to sanitary inspection under environmental health regulation before they may operate.", "Los establecimientos que preparan o venden alimentos están sujetos a inspección sanitaria bajo la reglamentación de salud ambiental antes de operar."),
    text("The sanitary/health permit documents that the premises passed inspection for food-handling and public-health conditions.", "El permiso sanitario acredita que el local aprobó la inspección de manejo de alimentos y condiciones de salud pública."),
    text("Prepare the premises for a Departamento de Salud sanitary inspection and submit the permit application for the food-handling activity.", "Prepara el local para la inspección sanitaria del Departamento de Salud y presenta la solicitud del permiso para la actividad de manejo de alimentos."),
    text("An issued sanitary permit authorizes the inspected food-handling activity at that location, subject to its conditions and renewal.", "El permiso sanitario emitido autoriza la actividad de manejo de alimentos inspeccionada en ese local, sujeto a sus condiciones y renovación."),
  ]),
  DOC_FIRE_CERT: concept("DOC_FIRE_CERT", [[condition("Q_FOOD_PREPARED", "Food prepared on site", "Alimentos preparados en el local", true)]], [PR_GUIDANCE_SOURCES.fire], [
    text("Commercial premises with food preparation or public occupancy require a fire-safety inspection before Cuerpo de Bomberos certifies the space.", "Los locales comerciales con preparación de alimentos u ocupación pública requieren inspección de seguridad contra incendios antes de la certificación."),
    text("The fire certification documents that the premises passed fire-code inspection for its occupancy and equipment, not general business compliance.", "El certificado de bomberos acredita que el local aprobó la inspección del código contra incendios para su ocupación y equipo, no el cumplimiento general del negocio."),
    text("Schedule the Cuerpo de Bomberos inspection for the premises and correct any noted deficiencies before the certificate is issued.", "Coordina la inspección del Cuerpo de Bomberos para el local y corrige las deficiencias señaladas antes de que se emita el certificado."),
    text("The issued fire certificate is required supporting evidence for the Permiso Único package; an inspection request alone is not certification.", "El certificado de bomberos emitido es evidencia requerida para el expediente del Permiso Único; solicitar la inspección no equivale a estar certificado."),
  ]),
  DOC_CFPM: concept("DOC_CFPM", [[condition("Q_FOOD_PREPARED", "Food prepared on site", "Alimentos preparados en el local", true)]], [PR_GUIDANCE_SOURCES.cfpm], [
    text("Establishments that prepare food must have a certified food protection manager on staff under Departamento de Salud regulation.", "Los establecimientos que preparan alimentos deben contar con un manejador de alimentos certificado según la reglamentación del Departamento de Salud."),
    text("The certified food protection manager documents that a specific staff member completed food-safety training as a food handler, not that the premises itself passed inspection.", "El manejador de alimentos certificado acredita que un miembro específico del personal completó adiestramiento de seguridad alimentaria, no que el local aprobó inspección."),
    text("Enroll the designated staff member as a certified food protection manager / food handler in an accredited course and keep the certification on file.", "Inscribe al empleado designado como manejador de alimentos certificado en un curso acreditado y conserva la certificación en el expediente."),
    text("A completed food protection manager certification qualifies that food handler to oversee food handling; it must stay current under the program's renewal terms.", "La certificación de manejador de alimentos completada habilita a ese empleado para supervisar el manejo de alimentos; debe mantenerse vigente según los términos de renovación."),
  ]),
  DOC_STORMWATER_PLAN: concept("DOC_STORMWATER_PLAN", [[municipality]], [PR_GUIDANCE_SOURCES.stormwater], [
    text("{municipality} is covered by an NPDES MS4 stormwater permit, which requires regulated businesses there to control runoff from their site.", "{municipality} está cubierto por un permiso NPDES MS4 de agua pluvial, que exige a los negocios regulados controlar la escorrentía de su predio."),
    text("The stormwater management plan documents how the site controls runoff and pollutants, not the business's other environmental permits.", "El plan de manejo de agua pluvial documenta cómo el predio controla la escorrentía y los contaminantes; no cubre otros permisos ambientales del negocio."),
    text("Prepare a site stormwater control plan addressing runoff and pollutant sources, and submit it as part of the permit package for {municipality}.", "Prepara un plan de control de escorrentía del predio que atienda las fuentes de contaminantes y preséntalo como parte del expediente de permisos para {municipality}."),
    text("An accepted plan documents the site's runoff controls for {municipality}'s MS4 program; conditions in the plan must still be maintained.", "Un plan aceptado documenta los controles de escorrentía del predio para el programa MS4 de {municipality}; las condiciones del plan deben mantenerse."),
  ]),
  DOC_NOISE_VARIANCE: concept("DOC_NOISE_VARIANCE", [[municipality]], [PR_GUIDANCE_SOURCES.noise], [
    text("{municipality} designates zones where activities generating elevated noise need a noise-control endorsement before operating there.", "{municipality} designa zonas donde las actividades que generan niveles elevados de ruido necesitan un endoso de control de ruido antes de operar."),
    text("The noise endorsement documents that the activity's expected noise levels were reviewed for the zone, not the activity's other licenses.", "El endoso de ruido acredita que se revisaron los niveles de ruido esperados de la actividad para la zona; no cubre otras licencias de la actividad."),
    text("Describe the activity's noise sources and expected levels, and request the noise-control endorsement through {municipality}'s permits office.", "Describe las fuentes de ruido de la actividad y los niveles esperados, y solicita el endoso de control de ruido en la oficina de permisos de {municipality}."),
    text("An issued endorsement authorizes the reviewed noise levels for that activity and zone, subject to its conditions and any complaints.", "El endoso emitido autoriza los niveles de ruido revisados para esa actividad y zona, sujeto a sus condiciones y a las quejas que se reciban."),
  ]),
  DOC_WASTE_COLLECTION_CONTRACT: concept("DOC_WASTE_COLLECTION_CONTRACT", [[municipality]], [PR_GUIDANCE_SOURCES.waste], [
    text("Commercial generators of solid waste in {municipality} must contract collection and disposal service rather than rely on residential collection.", "Los generadores comerciales de desperdicios sólidos en {municipality} deben contratar servicio de recolección y disposición en vez de la recolección residencial."),
    text("The waste-collection contract documents commercial disposal arrangements for the business, not the premises' other permits.", "El contrato de recolección de desperdicios documenta los arreglos de disposición comercial del negocio, no otros permisos del local."),
    text("Contract a licensed commercial waste hauler for {municipality} and keep the service agreement on file for the permit package.", "Contrata un transportista comercial de desperdicios autorizado para {municipality} y conserva el contrato de servicio en el expediente de permisos."),
    text("A signed contract documents commercial waste service is arranged; service must stay active for as long as the business generates waste.", "Un contrato firmado documenta que el servicio de desperdicios comerciales está arreglado; el servicio debe mantenerse activo mientras el negocio genere desperdicios."),
  ]),
  DOC_PARKING_COMPLIANCE: concept("DOC_PARKING_COMPLIANCE", [[municipality]], [PR_GUIDANCE_SOURCES.parking], [
    text("{municipality}'s use-permit review confirms the premises provide the off-street parking required for the proposed commercial activity.", "La revisión del permiso de uso en {municipality} confirma que el local cuenta con el estacionamiento fuera de la vía requerido para la actividad comercial propuesta."),
    text("Parking compliance documents that the site meets the off-street parking count for the activity, not the activity's use classification itself.", "El cumplimiento de estacionamiento acredita que el predio cumple con el número de espacios fuera de la vía requeridos para la actividad; no cubre la clasificación de uso."),
    text("Provide the site's parking layout and space count as part of the Permiso Único package for {municipality}'s review.", "Aporta el plano de estacionamiento del predio y el número de espacios como parte del expediente del Permiso Único para la revisión de {municipality}."),
    text("A confirmed parking count supports the use-permit application for {municipality}; changes to the site layout can affect that count later.", "Un conteo de estacionamiento confirmado respalda la solicitud del permiso de uso en {municipality}; cambios en el predio pueden afectar ese conteo después."),
  ]),
  DOC_LUMA_INTERCONNECTION: concept("DOC_LUMA_INTERCONNECTION", [[condition("Q_RENEWABLE_INSTALL", "Renewable energy system to be installed", "Instalación de sistema de energía renovable", true)]], [PR_GUIDANCE_SOURCES.luma], [
    text("A grid-connected solar system must be registered with LUMA Energy before it can legally operate. LUMA's interconnection review covers the system's technical requirements for parallel operation with the grid.", "Un sistema solar conectado a la red tiene que estar registrado con LUMA Energy antes de poder operar legalmente. La revisión de interconexión de LUMA cubre los requisitos técnicos para operar en paralelo con la red."),
    text("The interconnection registration is LUMA's record of the distributed generation system and its approval to connect, not the OGPe construction permit and not permission to operate.", "El registro de interconexión es el expediente de LUMA del sistema de generación distribuida y su aprobación para conectarse; no es el permiso de construcción de OGPe ni el permiso para operar."),
    text("Complete LUMA's interconnection registration with the system specifications and installer information. If the project needs an OGPe construction permit, finish OGPe first — LUMA requires the approved OGPe use permit before it processes the interconnection.", "Completa el registro de interconexión de LUMA con las especificaciones del sistema y la información del instalador. Si el proyecto necesita permiso de construcción de OGPe, termina OGPe primero — LUMA exige el permiso de uso aprobado de OGPe antes de tramitar la interconexión."),
    text("LUMA's interconnection approval authorizes the system to connect; the system still needs LUMA's Permission to Operate before it is switched on.", "La aprobación de interconexión de LUMA autoriza conectar el sistema; el sistema todavía necesita el Permiso para Operar de LUMA antes de encenderse."),
  ]),
  DOC_NET_METERING_AGREEMENT: concept("DOC_NET_METERING_AGREEMENT", [[condition("Q_RENEWABLE_INSTALL", "Renewable energy system to be installed", "Instalación de sistema de energía renovable", true)]], [PR_GUIDANCE_SOURCES.netMetering], [
    text("Commercial solar systems that export surplus energy to the grid operate under LUMA's interconnection and net metering agreement, which sets the metering and compensation terms.", "Los sistemas solares comerciales que exportan el excedente de energía a la red operan bajo el acuerdo de interconexión y medición neta de LUMA, que establece los términos de medición y compensación."),
    text("The net metering agreement documents the terms for parallel operation and exported-energy metering; it is not the interconnection registration itself and not permission to operate.", "El acuerdo de medición neta documenta los términos de operación en paralelo y medición de la energía exportada; no es el registro de interconexión ni el permiso para operar."),
    text("Execute LUMA's interconnection / net metering agreement for the commercial customer account tied to the installation address.", "Firma el acuerdo de interconexión y medición neta de LUMA para la cuenta comercial del cliente atada a la dirección de la instalación."),
    text("A countersigned agreement locks in the net metering terms for the system; keep it with the interconnection file until LUMA grants Permission to Operate.", "Un acuerdo firmado por ambas partes fija los términos de medición neta del sistema; consérvalo con el expediente de interconexión hasta que LUMA otorgue el Permiso para Operar."),
  ]),
  DOC_OGPE_CONSTRUCTION_PERMIT: concept("DOC_OGPE_CONSTRUCTION_PERMIT", [[condition("Q_SOLAR_MOUNTING", "Ground-mounted solar system", "Sistema solar instalado en el suelo", "Ground-mounted")], [condition("Q_SOLAR_SIZE", "System over 1 MW", "Sistema de más de 1 MW", "Over 1 MW")]], [PR_GUIDANCE_SOURCES.solarOgpe], [
    text("Solar photovoltaic systems larger than 1 MW, or not installed on the roof of an existing structure, must go through OGPe construction permitting before LUMA. Rooftop systems of 1 MW or less on existing structures are exempt from OGPe construction and use permits.", "Los sistemas solares fotovoltaicos de más de 1 MW, o que no se instalen en el techo de una estructura existente, tienen que pasar por los permisos de construcción de OGPe antes de LUMA. Los sistemas en techo de 1 MW o menos en estructuras existentes están exentos de los permisos de construcción y uso de OGPe."),
    text("The OGPe construction permit authorizes the solar installation's construction under the building and energy codes; it is separate from LUMA's interconnection registration.", "El permiso de construcción de OGPe autoriza la construcción de la instalación solar bajo los códigos de construcción y energía; es independiente del registro de interconexión de LUMA."),
    text("File the construction permit application through OGPe's Single Business Portal with the system plans and structural documentation, and complete it before filing the LUMA interconnection registration.", "Radica la solicitud del permiso de construcción en el Portal Único de OGPe (SBP) con los planos del sistema y la documentación estructural, y complétalo antes de radicar el registro de interconexión de LUMA."),
    text("An issued OGPe construction permit — and the resulting approved use permit — is what LUMA requires before it processes the interconnection; keep both permits in the project file.", "Un permiso de construcción de OGPe emitido — y el permiso de uso aprobado que resulta — es lo que LUMA exige antes de tramitar la interconexión; conserva ambos permisos en el expediente del proyecto."),
  ]),
};
