// ============================================================================
// Execution-history capture store (server-side).
//
// Writes capture events into normalized Supabase tables (submissions,
// question_responses, requirements_generated, document_validations,
// readiness_scores, scenario_patterns). Everything is best-effort and never
// affects the user flow. The JSON rules engine remains the source of truth;
// nothing here feeds back into requirement generation.
// ============================================================================

import { createHash, randomUUID } from "crypto";
import { getPool, isEnabled } from "./db";
import { COMPLIANCE_SCHEMA_SQL } from "../compliance/schema";
import { splitSqlStatements } from "./sqlStatements";
import { deriveObligationStatus, nextActionForStatus, validDateOnly } from "../compliance/dates";
import { renewalMetadataForDocuments, scheduleObligationNotifications } from "../compliance/server";
import type {
  CaptureEvent,
  SubmissionEvent,
  ValidationEvent,
  ReadinessEvent,
} from "./types";
import type { PoolClient } from "pg";

// Mirror of data/graph_schema.sql, applied once per process (idempotent).
const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS submissions (
  id UUID PRIMARY KEY, municipality TEXT, industry TEXT, business_type TEXT,
  location_type TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_submissions_bt ON submissions (business_type);
CREATE INDEX IF NOT EXISTS idx_submissions_created ON submissions (created_at);
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS business_structure TEXT;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS business_id UUID;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS claim_email TEXT;
CREATE INDEX IF NOT EXISTS idx_submissions_user ON submissions (user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_business ON submissions (business_id);
CREATE INDEX IF NOT EXISTS idx_submissions_claim_email ON submissions (claim_email) WHERE user_id IS NULL;

-- Users mirror of auth.users. Lazily upserted by the API on each authenticated
-- request so we never need to call into the auth schema directly.
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- Businesses owned by a user. A submission belongs to one business.
CREATE TABLE IF NOT EXISTS businesses (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_businesses_user ON businesses (user_id);

-- Persisted in-progress workflow snapshots so a user can save & resume mid-flow.
CREATE TABLE IF NOT EXISTS workflow_snapshots (
  submission_id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  business_id UUID,
  state JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_snapshots_user ON workflow_snapshots (user_id);

-- Deliverables generated by the user (reports, ZIP packages, submission bundles).
CREATE TABLE IF NOT EXISTS deliverables (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  business_id UUID,
  submission_id UUID,
  kind TEXT NOT NULL,                -- report | zip | submission
  filename TEXT NOT NULL,
  storage_path TEXT NOT NULL,        -- path inside the Supabase Storage bucket
  size_bytes BIGINT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_deliverables_user ON deliverables (user_id);
CREATE INDEX IF NOT EXISTS idx_deliverables_business ON deliverables (business_id);

CREATE TABLE IF NOT EXISTS question_responses (
  id BIGSERIAL PRIMARY KEY, submission_id UUID REFERENCES submissions(id) ON DELETE CASCADE,
  question_id TEXT NOT NULL, question_text TEXT, answer TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_qr_submission ON question_responses (submission_id);
CREATE TABLE IF NOT EXISTS requirements_generated (
  id BIGSERIAL PRIMARY KEY, submission_id UUID REFERENCES submissions(id) ON DELETE CASCADE,
  document_id TEXT, document_name TEXT NOT NULL, agency TEXT, reason TEXT,
  source_rule TEXT, mandatory BOOLEAN, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_rg_submission ON requirements_generated (submission_id);
CREATE INDEX IF NOT EXISTS idx_rg_document ON requirements_generated (document_name);
CREATE TABLE IF NOT EXISTS document_validations (
  id BIGSERIAL PRIMARY KEY, submission_id UUID REFERENCES submissions(id) ON DELETE CASCADE,
  business_type TEXT, document_type TEXT NOT NULL, validation_result TEXT, pass_fail BOOLEAN,
  confidence NUMERIC(5,2), expiration_status TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_docval_result ON document_validations (validation_result);
ALTER TABLE document_validations ADD COLUMN IF NOT EXISTS extracted_fields JSONB;
ALTER TABLE document_validations ADD COLUMN IF NOT EXISTS fields_found JSONB;
ALTER TABLE document_validations ADD COLUMN IF NOT EXISTS fields_missing JSONB;
ALTER TABLE document_validations ADD COLUMN IF NOT EXISTS user_id UUID;
CREATE INDEX IF NOT EXISTS idx_docval_user ON document_validations (user_id);
CREATE TABLE IF NOT EXISTS readiness_scores (
  id BIGSERIAL PRIMARY KEY, submission_id UUID REFERENCES submissions(id) ON DELETE CASCADE,
  business_type TEXT, score INTEGER, status TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_readiness_submission ON readiness_scores (submission_id);
ALTER TABLE readiness_scores ADD COLUMN IF NOT EXISTS user_id UUID;
CREATE INDEX IF NOT EXISTS idx_readiness_user ON readiness_scores (user_id);
CREATE TABLE IF NOT EXISTS scenario_patterns (
  id BIGSERIAL PRIMARY KEY, municipality TEXT, business_type TEXT,
  question_hash TEXT NOT NULL, requirements_hash TEXT NOT NULL,
  sample_answers JSONB NOT NULL DEFAULT '{}'::jsonb, sample_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
  occurrence_count BIGINT NOT NULL DEFAULT 1,
  first_seen TIMESTAMPTZ NOT NULL DEFAULT now(), last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (municipality, business_type, question_hash, requirements_hash));
CREATE INDEX IF NOT EXISTS idx_scenario_count ON scenario_patterns (occurrence_count DESC);

CREATE OR REPLACE VIEW v_submission_history AS
  SELECT s.id, s.created_at, s.municipality, s.industry, s.business_type,
         s.business_structure, s.location_type, s.user_id, s.business_id, s.business_name,
         rs.score AS readiness_score, rs.status AS readiness_status,
         (SELECT COUNT(*) FROM requirements_generated rg WHERE rg.submission_id = s.id) AS document_count
  FROM submissions s
  LEFT JOIN LATERAL (
    SELECT score, status FROM readiness_scores r WHERE r.submission_id = s.id
    ORDER BY created_at DESC LIMIT 1
  ) rs ON true
  ORDER BY s.created_at DESC;

DROP VIEW IF EXISTS v_submission_timeline;
CREATE VIEW v_submission_timeline AS
  -- The submissions table's PK is "id" — alias it so the view's column is
  -- named submission_id like the other two branches of the union.
  SELECT id AS submission_id, 'Submission Created' AS event, 'created' AS kind, created_at FROM submissions
  UNION ALL
  SELECT submission_id, 'Document Uploaded: ' || document_type, 'document', created_at FROM document_validations
  UNION ALL
  SELECT submission_id, 'Readiness Updated: ' || score || '%', 'readiness', created_at FROM readiness_scores;

CREATE OR REPLACE VIEW v_readiness_progression AS
  SELECT submission_id, score, status, created_at,
         ROW_NUMBER() OVER (PARTITION BY submission_id ORDER BY created_at) AS seq
  FROM readiness_scores;

CREATE OR REPLACE VIEW v_document_history AS
  SELECT dv.submission_id, dv.document_type, dv.validation_result, dv.pass_fail,
         dv.confidence, dv.expiration_status, dv.extracted_fields, dv.fields_found,
         dv.fields_missing, dv.created_at, s.business_type
  FROM document_validations dv JOIN submissions s ON s.id = dv.submission_id;

CREATE OR REPLACE VIEW v_submission_comparison AS
  SELECT s.id, s.municipality, s.industry, s.business_type, s.business_structure, s.location_type,
         rs.score AS readiness_score,
         (SELECT COUNT(*) FROM requirements_generated rg WHERE rg.submission_id = s.id) AS document_count,
         (SELECT array_agg(rg.document_name ORDER BY rg.document_name)
            FROM requirements_generated rg WHERE rg.submission_id = s.id) AS documents
  FROM submissions s
  LEFT JOIN LATERAL (
    SELECT score FROM readiness_scores r WHERE r.submission_id = s.id
    ORDER BY created_at DESC LIMIT 1
  ) rs ON true;
`;

export interface SchemaStatementFailure {
  /** First line of the offending statement — enough to identify it in the script. */
  statement: string;
  error: string;
}

let schemaReady: Promise<void> | null = null;
let schemaStatementFailures: SchemaStatementFailure[] = [];

/** Statements that failed the last time the schema was applied (empty = clean). */
export function schemaFailures(): SchemaStatementFailure[] {
  return schemaStatementFailures;
}

/**
 * Apply the schema one statement at a time.
 *
 * This used to be a single `pool.query()` over the whole concatenated script,
 * which made schema creation all-or-nothing: ONE rejected statement aborted the
 * batch, so no table was ever created, and because `ensureSchema()` sits on the
 * login path every user was locked out with an opaque 503. Applying statements
 * individually means an unusable statement costs only the object it defines,
 * and the failure is reported precisely instead of anonymously.
 */
async function applySchema(pool: NonNullable<ReturnType<typeof getPool>>): Promise<void> {
  // Fail fast and loudly on a dead connection: without this probe each of the
  // ~100 statements below would separately wait out the connection timeout
  // before we could report what is really one problem.
  await pool.query("SELECT 1");

  const failures: SchemaStatementFailure[] = [];
  for (const statement of splitSqlStatements(`${SCHEMA_SQL}\n${COMPLIANCE_SCHEMA_SQL}`)) {
    try {
      await pool.query(statement);
    } catch (e) {
      failures.push({
        // Leading `--` comments are stripped so the label names the DDL that
        // failed rather than the prose above it.
        statement: (statement.replace(/^(?:\s*--[^\n]*\n)*/, "").split("\n")[0] || statement).slice(0, 120),
        error: (e as Error).message,
      });
    }
  }
  schemaStatementFailures = failures;
  if (failures.length) {
    console.error(`[graph] ${failures.length} schema statement(s) failed:`);
    for (const f of failures) console.error(`[graph]   ${f.statement} -> ${f.error}`);
  }
}

// Exported so the user-account / business / snapshot / deliverable APIs can
// guarantee their tables exist before issuing queries — even if no capture
// event has run yet this process.
//
// On failure we clear the cached promise so the next request can retry —
// otherwise a single bootstrap error would stick until the process restarted.
export async function ensureSchema(): Promise<void> {
  if (!schemaReady) {
    const pool = getPool();
    schemaReady = pool
      ? applySchema(pool).catch((e) => {
          schemaReady = null;
          throw e;
        })
      : Promise.resolve();
  }
  return schemaReady;
}

function hash(value: unknown): string {
  return createHash("sha1").update(JSON.stringify(value)).digest("hex").slice(0, 16);
}

// ---- event handlers -----------------------------------------------------

async function captureSubmission(
  c: PoolClient,
  e: SubmissionEvent,
  ctx: CaptureContext
): Promise<void> {
  // Header row (idempotent on re-capture of the same submission id).
  await c.query(
    `INSERT INTO submissions (id, municipality, industry, business_type, business_structure,
       location_type, business_name, business_id, matter_id, user_id, claim_email)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
     ON CONFLICT (id) DO UPDATE SET
       municipality=EXCLUDED.municipality, industry=EXCLUDED.industry,
       business_type=EXCLUDED.business_type, business_structure=EXCLUDED.business_structure,
       location_type=EXCLUDED.location_type, business_name=EXCLUDED.business_name,
       business_id=COALESCE(EXCLUDED.business_id, submissions.business_id),
       matter_id=COALESCE(EXCLUDED.matter_id, submissions.matter_id),
       user_id=COALESCE(EXCLUDED.user_id, submissions.user_id),
       claim_email=COALESCE(EXCLUDED.claim_email, submissions.claim_email),
       updated_at=now()`,
    [
      e.submission_id, e.municipality ?? null, e.industry ?? null, e.business_type ?? null,
      e.business_structure ?? null, e.location_type ?? null,
      e.business_name ?? null, e.business_id ?? null, e.matter_id ?? null,
      ctx.userId ?? null, e.claim_email ?? null,
    ]
  );

  // Replace child rows so a re-capture stays consistent (no duplicates).
  await c.query(`DELETE FROM question_responses WHERE submission_id=$1`, [e.submission_id]);
  await c.query(`DELETE FROM requirements_generated WHERE submission_id=$1`, [e.submission_id]);

  for (const a of e.answers) {
    await c.query(
      `INSERT INTO question_responses (submission_id, question_id, question_text, answer)
       VALUES ($1,$2,$3,$4)`,
      [e.submission_id, a.question_id, a.question, String(a.answer)]
    );
  }

  for (const r of e.requirements) {
    await c.query(
      `INSERT INTO requirements_generated
         (submission_id, document_id, document_name, agency, reason, source_rule, mandatory)
       VALUES ($1,$2,$3,$4,$5,$6,$7)`,
      [e.submission_id, r.document_id ?? null, r.document, r.agency ?? null, r.reason ?? null, r.source_rule ?? null, r.mandatory ?? null]
    );
  }

  // Project authoritative engine output into the persistent compliance model.
  // This projection never creates requirements on its own; it mirrors only the
  // requirements supplied by the deterministic rules engine above.
  if (ctx.userId && e.business_id && e.matter_id) {
    const access = await c.query<{ workspace_id: string | null }>(
      `SELECT workspace_id FROM businesses WHERE id = $1 AND user_id = $2 AND archived = false`,
      [e.business_id, ctx.userId]
    );
    if (access.rows[0]) {
      await c.query(
        `UPDATE businesses SET
           name = COALESCE(NULLIF($3,''), name),
           legal_name = COALESCE(NULLIF($3,''), legal_name, name),
           municipality = COALESCE(NULLIF($4,''), municipality),
           industry = COALESCE(NULLIF($5,''), industry),
           business_type = COALESCE(NULLIF($6,''), business_type),
           business_structure = COALESCE(NULLIF($7,''), business_structure),
           updated_at = now()
         WHERE id = $1 AND user_id = $2`,
        [e.business_id, ctx.userId, e.business_name ?? "", e.municipality ?? "", e.industry ?? "", e.business_type ?? "", e.business_structure ?? ""]
      );
      await c.query(
        `UPDATE matters SET submission_id = $1, status = CASE WHEN status = 'DRAFT' THEN 'IN_PROGRESS' ELSE status END,
                            updated_at = now()
          WHERE id = $2 AND business_id = $3 AND user_id = $4`,
        [e.submission_id, e.matter_id, e.business_id, ctx.userId]
      );
      const renewalMetadata = await renewalMetadataForDocuments(
        c,
        e.requirements.map((requirement) => requirement.document_id).filter((id): id is string => Boolean(id))
      );
      for (const requirement of e.requirements) {
        const requirementId = requirement.document_id || requirement.document;
        const renewal = renewalMetadata.get(requirementId);
        await c.query(
          `INSERT INTO obligations
             (id, business_id, matter_id, requirement_id, graph_entity_id, name, agency,
              status, mandatory, source, source_reference, renewal_frequency_months,
              renewal_reference, next_action)
           VALUES ($1,$2,$3,$4,$5,$6,$7,'MISSING',$8,'REGULATORY_GRAPH',$9,$10,$11,'Upload current evidence')
           ON CONFLICT (matter_id, requirement_id, cycle_index) DO UPDATE SET
             name = EXCLUDED.name, agency = EXCLUDED.agency, mandatory = EXCLUDED.mandatory,
             source_reference = EXCLUDED.source_reference,
             renewal_frequency_months = COALESCE(EXCLUDED.renewal_frequency_months, obligations.renewal_frequency_months),
             renewal_reference = COALESCE(EXCLUDED.renewal_reference, obligations.renewal_reference), updated_at = now()`,
          [randomUUID(), e.business_id, e.matter_id, requirementId, renewal?.graphEntityId ?? requirementId,
            requirement.document, requirement.agency ?? null, requirement.mandatory ?? true,
            requirement.source_rule ?? null, renewal?.frequencyMonths ?? null, renewal?.reference ?? null]
        );
      }
    }
  }

  // Scenario-pattern frequency counter.
  const answerMap: Record<string, string | boolean> = {};
  for (const a of e.answers) answerMap[a.question_id] = a.answer;
  const docList = e.requirements.map((r) => r.document);
  const questionHash = hash(answerMap);
  const requirementsHash = hash([...docList].sort());

  await c.query(
    `INSERT INTO scenario_patterns
       (municipality, business_type, question_hash, requirements_hash, sample_answers, sample_documents)
     VALUES ($1,$2,$3,$4,$5,$6)
     ON CONFLICT (municipality, business_type, question_hash, requirements_hash) DO UPDATE
       SET occurrence_count = scenario_patterns.occurrence_count + 1, last_seen = now()`,
    [
      e.municipality ?? "", e.business_type ?? "", questionHash, requirementsHash,
      JSON.stringify(answerMap), JSON.stringify(docList),
    ]
  );
}

async function captureValidation(c: PoolClient, e: ValidationEvent, ctx: CaptureContext): Promise<void> {
  // Inherit user_id from the parent submission if the client didn't pass one.
  const userId = ctx.userId ?? (await ownerForSubmission(c, e.submission_id));
  const inserted = await c.query<{ id: number }>(
    `INSERT INTO document_validations
       (submission_id, business_type, document_type, validation_result, pass_fail,
        confidence, expiration_status, extracted_fields, fields_found, fields_missing, user_id)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
     RETURNING id`,
    [
      sub(e.submission_id), e.business_type ?? null, e.document_type, e.validation_result,
      e.pass_fail, e.confidence, e.expiration_status,
      e.extracted_fields ? JSON.stringify(e.extracted_fields) : null,
      e.fields_found ? JSON.stringify(e.fields_found) : null,
      e.fields_missing ? JSON.stringify(e.fields_missing) : null,
      userId,
    ]
  );

  if (!userId || !e.submission_id) return;
  const scope = await c.query<{
    business_id: string | null;
    matter_id: string | null;
    workspace_id: string | null;
    business_name: string | null;
  }>(
    `SELECT s.business_id, s.matter_id, b.workspace_id, COALESCE(b.legal_name, b.name) AS business_name
       FROM submissions s LEFT JOIN businesses b ON b.id = s.business_id
      WHERE s.id = $1 AND s.user_id = $2`,
    [e.submission_id, userId]
  );
  const owner = scope.rows[0];
  if (!owner?.business_id) return;

  const requirementId = e.requirement_id ?? null;
  const obligation = requirementId && owner.matter_id
    ? (await c.query<{
        id: string;
        name: string;
        renewal_frequency_months: number | null;
      }>(
        `SELECT id, name, renewal_frequency_months FROM obligations
          WHERE matter_id = $1 AND requirement_id = $2 ORDER BY cycle_index DESC LIMIT 1`,
        [owner.matter_id, requirementId]
      )).rows[0]
    : null;
  const extracted = e.extracted_fields ?? {};
  const expirationDate = validDateOnly(extracted.expiration_date);
  const issueDate = validDateOnly(extracted.issue_date);
  const evidenceState = e.validation_result === "PASS" ? "VERIFIED"
    : e.validation_result === "NEEDS_REVIEW" ? "NEEDS_REVIEW" : "FAILED";
  const status = deriveObligationStatus({
    evidenceState,
    dueDate: expirationDate,
    expectsRenewal: Boolean(obligation?.renewal_frequency_months || expirationDate),
  });
  await c.query(
    `INSERT INTO evidence
       (id, user_id, business_id, matter_id, obligation_id, validation_id,
        original_filename, mime_type, size_bytes, document_type, review_status,
        extracted_fields, extraction_confidence, issue_date, expiration_date,
        date_source, source_reference, reviewed_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,now())`,
    [randomUUID(), userId, owner.business_id, owner.matter_id, obligation?.id ?? null,
      inserted.rows[0]?.id ?? null, e.original_filename || e.document_type,
      e.mime_type ?? null, e.size_bytes ?? null, e.document_type,
      evidenceState === "VERIFIED" ? "VERIFIED" : evidenceState === "NEEDS_REVIEW" ? "NEEDS_REVIEW" : "REJECTED",
      JSON.stringify(extracted), Math.max(0, Math.min(1, e.confidence / 100)),
      issueDate, expirationDate, expirationDate ? "DOCUMENT_EXTRACTED" : "UNKNOWN",
      expirationDate ? `Document extraction: ${e.original_filename || e.document_type}` : null]
  );
  if (obligation) {
    await c.query(
      `UPDATE obligations SET status = $2, due_date = COALESCE($3::date, due_date),
          due_date_source = CASE WHEN $3::date IS NOT NULL THEN 'DOCUMENT_EXTRACTED' ELSE due_date_source END,
          due_date_confidence = CASE WHEN $3::date IS NOT NULL THEN $4 ELSE due_date_confidence END,
          source_reference = CASE WHEN $3::date IS NOT NULL THEN $5 ELSE source_reference END,
          verified_at = CASE WHEN $6 = 'VERIFIED' THEN now() ELSE verified_at END,
          next_action = $7, updated_at = now()
        WHERE id = $1`,
      [obligation.id, status, expirationDate, Math.max(0, Math.min(1, e.confidence / 100)),
        expirationDate ? `Document extraction: ${e.original_filename || e.document_type}` : null,
        evidenceState, nextActionForStatus(status)]
    );
    if (expirationDate) {
      await scheduleObligationNotifications(c, {
        userId,
        workspaceId: owner.workspace_id,
        businessId: owner.business_id,
        businessName: owner.business_name || "Business",
        obligationId: obligation.id,
        obligationName: obligation.name,
        dueDate: expirationDate,
      });
    }
  }
}

async function captureReadiness(c: PoolClient, e: ReadinessEvent, ctx: CaptureContext): Promise<void> {
  const userId = ctx.userId ?? (await ownerForSubmission(c, e.submission_id));
  await c.query(
    `INSERT INTO readiness_scores (submission_id, business_type, score, status, user_id)
     VALUES ($1,$2,$3,$4,$5)`,
    [sub(e.submission_id), e.business_type ?? null, e.score, e.status, userId]
  );
  if (e.submission_id) {
    await c.query(
      `UPDATE matters m SET readiness_score = $2,
          status = CASE WHEN $2 >= 90 THEN 'READY' WHEN m.status = 'DRAFT' THEN 'IN_PROGRESS' ELSE m.status END,
          updated_at = now()
        FROM submissions s
       WHERE s.id = $1 AND s.matter_id = m.id AND ($3::uuid IS NULL OR m.user_id = $3)`,
      [e.submission_id, e.score, userId]
    );
  }
}

async function ownerForSubmission(c: PoolClient, id: string): Promise<string | null> {
  if (!id) return null;
  try {
    const { rows } = await c.query<{ user_id: string | null }>(
      `SELECT user_id FROM submissions WHERE id = $1`, [id]
    );
    return rows[0]?.user_id ?? null;
  } catch { return null; }
}

// A validation/readiness event can arrive before its submission row exists
// (rare race). Treat a missing/empty id as null so the FK stays valid.
function sub(id: string | undefined): string | null {
  return id && id.length > 0 ? id : null;
}

// Optional auth context — when present, the captured rows are associated with
// the user. Anonymous capture still works (userId stays null).
export interface CaptureContext {
  userId?: string | null;
}

// ---- public entry point -------------------------------------------------

export async function capture(
  event: CaptureEvent,
  ctx: CaptureContext = {}
): Promise<{ ok: boolean; stored: boolean }> {
  if (!isEnabled()) return { ok: true, stored: false };
  const pool = getPool();
  if (!pool) return { ok: true, stored: false };
  await ensureSchema();
  const c = await pool.connect();
  try {
    await c.query("BEGIN");
    if (event.kind === "submission") await captureSubmission(c, event, ctx);
    else if (event.kind === "validation") await captureValidation(c, event, ctx);
    else if (event.kind === "readiness") await captureReadiness(c, event, ctx);
    await c.query("COMMIT");
    return { ok: true, stored: true };
  } catch (err) {
    await c.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    c.release();
  }
}
