// ============================================================================
// Server-side branded PDF generation for enterprise reports (Phase 3).
// Uses pdf-lib (already a dependency). Produces a clean, print-ready PDF:
// org branding header (workspace_branding), report title, generation + data-
// as-of timestamps (America/New_York), applied filters, methodology notes,
// summary, and a paginated record table with per-record SmartPR URLs.
// ============================================================================

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export interface PdfColumn {
  key: string;
  label: string;
  /** relative width weight */
  w: number;
}

export interface ReportPdfInput {
  orgName: string;
  primaryColor: string; // hex, e.g. "#245c5c"
  reportTitle: string;
  generatedAt: Date;
  dataAsOf: Date;
  filtersApplied: string[];
  methodology: string[];
  summary: Array<{ label: string; value: string }>;
  columns: PdfColumn[];
  records: Array<Record<string, unknown>>;
  recordUrl: (record: Record<string, unknown>) => string | null;
  confidentialityNote?: string;
}

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const m = /^#?([0-9a-fA-F]{6})$/.exec((hex || "").trim());
  if (!m) return { r: 0x24, g: 0x5c, b: 0x5c }; // SmartPR brand fallback
  const n = parseInt(m[1], 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

function fmtET(d: Date): string {
  try {
    return (
      d.toLocaleString("en-US", {
        timeZone: "America/New_York",
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      }) + " ET"
    );
  } catch {
    return d.toISOString();
  }
}

function cellText(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  return String(v);
}

/** Greedy word-wrap for a single paragraph. */
function wrap(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const trial = line ? line + " " + word : word;
    if (font.widthOfTextAtSize(trial, size) <= maxWidth || !line) {
      line = trial;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

export async function generateReportPdf(input: ReportPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const brand = hexToRgb(input.primaryColor);
  const brandColor = rgb(brand.r / 255, brand.g / 255, brand.b / 255);
  const ink = rgb(0.09, 0.09, 0.09);
  const muted = rgb(0.35, 0.35, 0.35);
  const faint = rgb(0.45, 0.45, 0.45);
  const zebra = rgb(0.96, 0.96, 0.94);
  const rule = rgb(0.85, 0.85, 0.82);
  const white = rgb(1, 1, 1);

  let page: PDFPage = doc.addPage([PAGE_W, PAGE_H]);
  let pageNum = 1;
  let y = PAGE_H - MARGIN;

  const footer = (p: PDFPage, n: number) => {
    p.drawText(
      `Confidential — generated by SmartPR Enterprise  •  Page ${n}`,
      { x: MARGIN, y: 32, size: 7, font, color: faint }
    );
    p.drawText(input.orgName, {
      x: PAGE_W - MARGIN - font.widthOfTextAtSize(input.orgName, 7),
      y: 32,
      size: 7,
      font,
      color: faint,
    });
  };

  const newPage = () => {
    footer(page, pageNum);
    page = doc.addPage([PAGE_W, PAGE_H]);
    pageNum += 1;
    y = PAGE_H - MARGIN;
  };
  const ensure = (needed: number) => {
    if (y - needed < 48) newPage();
  };

  // ---- Header band ---------------------------------------------------------
  page.drawRectangle({ x: 0, y: PAGE_H - 92, width: PAGE_W, height: 92, color: brandColor });
  page.drawText(input.orgName, { x: MARGIN, y: PAGE_H - 46, size: 17, font: bold, color: white });
  page.drawText(input.reportTitle, {
    x: MARGIN,
    y: PAGE_H - 66,
    size: 11,
    font,
    color: rgb(1, 1, 1),
  });
  y = PAGE_H - 92 - 22;

  // ---- Meta block ------------------------------------------------------------
  const meta: Array<[string, string]> = [
    ["Generated", fmtET(input.generatedAt)],
    ["Data as of", fmtET(input.dataAsOf)],
    ["Applied filters", input.filtersApplied.length ? "" : "None — full portfolio scope"],
  ];
  for (const [label, value] of meta) {
    ensure(16);
    page.drawText(label + ":", { x: MARGIN, y, size: 9, font: bold, color: ink });
    const lx = MARGIN + bold.widthOfTextAtSize(label + ": ", 9);
    for (const line of wrap(value, font, 9, CONTENT_W - (lx - MARGIN))) {
      ensure(14);
      page.drawText(line, { x: lx, y, size: 9, font, color: muted });
      y -= 13;
    }
    y -= 2;
  }
  if (input.filtersApplied.length) {
    for (const f of input.filtersApplied) {
      for (const line of wrap("• " + f, font, 9, CONTENT_W - 12)) {
        ensure(14);
        page.drawText(line, { x: MARGIN + 12, y, size: 9, font, color: muted });
        y -= 13;
      }
    }
  }
  y -= 10;

  const sectionTitle = (t: string) => {
    ensure(30);
    y -= 4;
    page.drawText(t, { x: MARGIN, y, size: 12, font: bold, color: brandColor });
    y -= 8;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: rule });
    y -= 14;
  };

  // ---- Methodology -------------------------------------------------------------
  sectionTitle("Methodology");
  for (const note of input.methodology) {
    for (const line of wrap("•  " + note, font, 8.5, CONTENT_W - 12)) {
      ensure(14);
      page.drawText(line, { x: MARGIN + 12, y, size: 8.5, font, color: ink });
      y -= 12;
    }
    y -= 2;
  }
  y -= 8;

  // ---- Summary -------------------------------------------------------------------
  if (input.summary.length) {
    sectionTitle("Summary");
    for (const s of input.summary) {
      ensure(16);
      page.drawText(s.label, { x: MARGIN, y, size: 9, font, color: muted });
      const vx = PAGE_W - MARGIN - bold.widthOfTextAtSize(s.value, 9);
      page.drawText(s.value, { x: Math.max(vx, MARGIN + 200), y, size: 9, font: bold, color: ink });
      y -= 15;
    }
    y -= 8;
  }

  // ---- Records table ---------------------------------------------------------------
  sectionTitle(`Records (${input.records.length})`);
  // Proportional widths (c.w) keep every column legible; text wraps inside
  // narrow columns instead of being dropped.
  const cols = input.columns.length ? input.columns : [{ key: "detail", label: "Detail", w: 1 }];
  const totalW = cols.reduce((s, c) => s + c.w, 0) || 1;
  const colX: number[] = [];
  {
    let x = MARGIN;
    for (const c of cols) {
      colX.push(x);
      x += (c.w / totalW) * CONTENT_W;
    }
  }
  const colWidth = (i: number) =>
    (i + 1 < cols.length ? colX[i + 1] : PAGE_W - MARGIN) - colX[i] - 6;

  const drawHeader = () => {
    ensure(22);
    page.drawRectangle({
      x: MARGIN,
      y: y - 4,
      width: CONTENT_W,
      height: 18,
      color: brandColor,
    });
    cols.forEach((c, i) => {
      page.drawText(c.label, { x: colX[i] + 3, y: y, size: 8, font: bold, color: white });
    });
    y -= 20;
  };
  drawHeader();

  input.records.forEach((rec, idx) => {
    const cellLines = cols.map((c, i) =>
      wrap(cellText(rec[c.key]), font, 8, Math.max(colWidth(i), 40))
    );
    const rowH = Math.max(...cellLines.map((l) => l.length)) * 11 + 4;
    const url = input.recordUrl(rec);
    const urlLines = url ? wrap("Record: " + url, font, 7, CONTENT_W - 12) : [];
    ensure(rowH + urlLines.length * 10 + 8);

    if (idx % 2 === 1) {
      page.drawRectangle({ x: MARGIN, y: y - rowH + 12, width: CONTENT_W, height: rowH, color: zebra });
    }
    const top = y;
    cellLines.forEach((lines, i) => {
      lines.forEach((line, li) => {
        page.drawText(line, { x: colX[i] + 3, y: top - li * 11, size: 8, font, color: ink });
      });
    });
    y = top - rowH + 2;
    for (const line of urlLines) {
      page.drawText(line, { x: MARGIN + 12, y, size: 7, font, color: faint });
      y -= 10;
    }
    y -= 6;
    // re-draw header if we crossed a page boundary mid-table
    if (y < 60 && idx < input.records.length - 1) {
      newPage();
      drawHeader();
    }
  });

  if (input.confidentialityNote) {
    y -= 10;
    ensure(30);
    for (const line of wrap(input.confidentialityNote, font, 8, CONTENT_W)) {
      page.drawText(line, { x: MARGIN, y, size: 8, font, color: faint });
      y -= 11;
    }
  }

  footer(page, pageNum);
  return doc.save();
}
