// ============================================================================
// Knowledge Graph Reasoning Paths — v1 seed data.
// Human-authored, human-reviewed. Every condition carries a real citation.
// "kb-silent" confidence marks areas where the KB does not yet model the
// mechanics — those are research backlog, not invented law.
// See docs/reasoning-paths-design.md §6.
// ============================================================================

import type { DecisionCondition, ProcessVariant, ReasoningGraph, Scenario } from "./types";

export const RP_CONDITIONS: DecisionCondition[] = [
  {
    id: "COND_NEW_BUSINESS",
    label: "New business",
    triggerSummary: "A new business is being formed and does not yet hold operating permits.",
    expr: { all: [{ fact: "new_business", op: "eq", value: true }] },
    sourceId: "Ley 164-2009, Art. 1.01(C)",
    locator: "Art. 1.01(C)",
    confidence: "high",
  },
  {
    id: "COND_EXISTING_BUSINESS",
    label: "Existing business",
    triggerSummary: "An already-operating business that holds (or should hold) permits.",
    expr: { all: [{ fact: "existing_business", op: "eq", value: true }] },
    sourceId: "Arts. 7.200-7.207, Ley 107-2020 (Código Municipal de Puerto Rico)",
    locator: "Título VII",
    confidence: "high",
  },
  {
    id: "COND_EXISTING_LOCATION",
    label: "Existing location",
    triggerSummary: "The business will operate at an already-built, previously occupied location.",
    expr: { all: [{ fact: "existing_location", op: "eq", value: true }] },
    sourceId: "Art. 8.4A, Ley 161-2009 (23 L.P.R.A. § 9018c-1), añadido por Ley 19-2017",
    locator: "Art. 8.4A",
    confidence: "high",
  },
  {
    id: "COND_CONSTRUCTION_REQUIRED",
    label: "Construction required",
    triggerSummary: "New construction, expansion, or structural work is planned at the site.",
    expr: { all: [{ fact: "construction_required", op: "eq", value: true }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "high",
  },
  {
    id: "COND_REMODELING",
    label: "Remodeling",
    triggerSummary: "Interior remodel or rehabilitation is planned without expanding the footprint.",
    expr: { all: [{ fact: "remodeling", op: "eq", value: true }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "high",
  },
  {
    id: "COND_OWNERSHIP_CHANGED",
    label: "Ownership changed",
    triggerSummary: "The business changed hands — permits and municipal obligations transfer with it.",
    expr: { all: [{ fact: "ownership_changed", op: "eq", value: true }] },
    sourceId: "Ley 107-2020 (Código Municipal de Puerto Rico)",
    locator: "Código Municipal",
    confidence: "kb-silent",
  },
  {
    id: "COND_USE_CHANGED",
    label: "Use changed",
    triggerSummary: "The activity or use at the location changed from what was previously authorized.",
    expr: { all: [{ fact: "use_changed", op: "eq", value: true }] },
    sourceId: "Art. 8.4A, Ley 161-2009 (23 L.P.R.A. § 9018c-1), añadido por Ley 19-2017",
    locator: "Art. 8.4A",
    confidence: "medium",
  },
  {
    id: "COND_SAME_USE",
    label: "Same use",
    triggerSummary: "The activity or use at the location stays the same as previously authorized.",
    expr: { all: [{ fact: "same_use", op: "eq", value: true }] },
    sourceId: "Art. 8.4A, Ley 161-2009 (23 L.P.R.A. § 9018c-1), añadido por Ley 19-2017",
    locator: "Art. 8.4A",
    confidence: "medium",
  },
  {
    id: "COND_PERMIT_RENEWAL",
    label: "Permit renewal",
    triggerSummary: "The business is renewing existing permits with no other changes.",
    expr: { all: [{ fact: "permit_renewal", op: "eq", value: true }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "medium",
  },
  {
    id: "COND_RESIDENTIAL_USE",
    label: "Residential use",
    triggerSummary: "The project is residential rather than commercial.",
    expr: { all: [{ fact: "residential_use", op: "eq", value: true }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "kb-silent",
  },
  {
    id: "COND_COMMERCIAL_USE",
    label: "Commercial use",
    triggerSummary: "The project is a commercial activity subject to operating permits.",
    expr: { all: [{ fact: "commercial_use", op: "eq", value: true }] },
    sourceId: "Art. 8.4A, Ley 161-2009 (23 L.P.R.A. § 9018c-1), añadido por Ley 19-2017",
    locator: "Art. 8.4A",
    confidence: "high",
  },
  {
    id: "COND_UTILITY_CONNECTION",
    label: "Utility connection",
    triggerSummary: "A new utility service connection (electric and/or water) is needed.",
    expr: { all: [{ fact: "utility_connection", op: "eq", value: true }] },
    sourceId: "LUMA / AAA service regulations",
    locator: "n/a",
    confidence: "kb-silent",
  },
  {
    id: "COND_SUBDIVISION",
    label: "Subdivision",
    triggerSummary: "The parcel is being segregated or subdivided.",
    expr: { all: [{ fact: "subdivision", op: "eq", value: true }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "kb-silent",
  },
  {
    id: "COND_RESTAURANT",
    label: "Restaurant activity",
    triggerSummary: "The business is a restaurant (food establishment).",
    expr: { all: [{ fact: "business_activity", op: "eq", value: "restaurant" }] },
    sourceId: "Ley 81-1912 (Ley del Departamento de Salud), 3 LPRA § 178",
    locator: "3 LPRA § 178",
    confidence: "medium",
  },
  {
    id: "COND_DAYCARE",
    label: "Daycare activity",
    triggerSummary: "The business is a childcare / daycare establishment.",
    expr: { all: [{ fact: "business_activity", op: "eq", value: "daycare" }] },
    sourceId: "Ley 173-2016 (Licenciamiento de Establecimientos de Cuidado, Desarrollo y Aprendizaje)",
    locator: "Ley 173-2016",
    confidence: "high",
  },
  {
    id: "COND_PHARMACY",
    label: "Pharmacy activity",
    triggerSummary: "The business is a pharmacy.",
    expr: { all: [{ fact: "business_activity", op: "eq", value: "pharmacy" }] },
    sourceId: "Ley 81-1912, 3 LPRA § 178; Ley 247-2004 (farmacias)",
    locator: "Ley 247-2004",
    confidence: "high",
  },
  {
    id: "COND_SOLAR",
    label: "Solar activity",
    triggerSummary: "The project involves solar / renewable energy generation.",
    expr: { all: [{ fact: "business_activity", op: "eq", value: "solar" }] },
    sourceId: "Law 114-2007 Art. 9; CEPR-MI-2014-0001",
    locator: "Art. 9",
    confidence: "high",
  },
  {
    id: "COND_MANUFACTURING",
    label: "Manufacturing activity",
    triggerSummary: "The business is a manufacturing facility.",
    expr: { all: [{ fact: "business_activity", op: "eq", value: "manufacturing" }] },
    sourceId: "Ley 161-2009, Ley para la Reforma del Proceso de Permisos (23 L.P.R.A. § 9011 et seq.)",
    locator: "Ley 161-2009",
    confidence: "kb-silent",
  },
  {
    id: "COND_FOOD_SERVICE",
    label: "Food service",
    triggerSummary: "Food is prepared or served on site.",
    expr: { all: [{ fact: "food_service", op: "eq", value: true }] },
    sourceId: "Ley 81-1912 (Ley del Departamento de Salud), 3 LPRA § 178",
    locator: "3 LPRA § 178",
    confidence: "high",
  },
  {
    id: "COND_GRID_INTERCONNECTION",
    label: "Grid interconnection",
    triggerSummary: "The energy system will operate interconnected (in parallel) with the LUMA grid.",
    expr: { all: [{ fact: "grid_interconnection", op: "eq", value: true }] },
    sourceId: "Law 114-2007 Art. 9; CEPR-MI-2014-0001",
    locator: "§ 6.1",
    confidence: "high",
  },
  {
    id: "COND_CORPORATION",
    label: "Corporation entity",
    triggerSummary: "The business entity is a corporation (as opposed to LLC, sole proprietorship, etc.).",
    expr: { all: [{ fact: "entity_type", op: "eq", value: "corporation" }] },
    sourceId: "Ley 164-2009, Art. 1.01(C)",
    locator: "Art. 1.01(C)",
    confidence: "high",
  },
];

export const RP_SCENARIOS: Scenario[] = [
  {
    id: "SCN_NEW_BIZ_EXISTING_LOCATION",
    label: "New business in an existing location, no construction",
    description: "A new business opens at an already-built, previously occupied site with no construction or remodeling.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_EXISTING_LOCATION"],
    excludedConditions: ["COND_CONSTRUCTION_REQUIRED", "COND_REMODELING"],
  },
  {
    id: "SCN_NEW_BIZ_REMOVDELING",
    label: "New business with remodeling",
    description: "A new business opens at a site that needs interior remodeling before operating.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_REMODELING"],
    excludedConditions: [],
  },
  {
    id: "SCN_EXISTING_BIZ_OWNERSHIP_CHANGE",
    label: "Existing business changing ownership",
    description: "An operating business changes hands with no change of use, construction, or remodeling.",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_OWNERSHIP_CHANGED"],
    excludedConditions: ["COND_USE_CHANGED", "COND_CONSTRUCTION_REQUIRED", "COND_REMODELING"],
  },
  {
    id: "SCN_EXISTING_BIZ_CHANGE_OF_USE",
    label: "Existing business changing use",
    description: "An operating business or location changes the authorized activity/use.",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_USE_CHANGED"],
    excludedConditions: [],
  },
  {
    id: "SCN_EXISTING_BIZ_RENEWAL",
    label: "Existing business renewing permits",
    description: "An operating business renews its permits with no other changes.",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_PERMIT_RENEWAL"],
    excludedConditions: [
      "COND_CONSTRUCTION_REQUIRED",
      "COND_OWNERSHIP_CHANGED",
      "COND_USE_CHANGED",
      "COND_REMODELING",
    ],
  },
  {
    id: "SCN_NEW_COMMERCIAL_CONSTRUCTION",
    label: "New commercial construction",
    description: "A new commercial business builds new structures or expands the footprint.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_COMMERCIAL_USE", "COND_CONSTRUCTION_REQUIRED"],
    excludedConditions: [],
  },
  {
    id: "SCN_RESIDENTIAL_USE",
    label: "Residential use",
    description: "The project is residential; commercial operating permits do not apply.",
    requiredConditions: ["COND_RESIDENTIAL_USE"],
    excludedConditions: [],
  },
  {
    id: "SCN_COMMERCIAL_UTILITY",
    label: "Commercial utility connection",
    description: "A commercial operation needs a new electric/water service connection.",
    requiredConditions: ["COND_COMMERCIAL_USE", "COND_UTILITY_CONNECTION"],
    excludedConditions: [],
  },
  {
    id: "SCN_RESIDENTIAL_UTILITY",
    label: "Residential utility connection",
    description: "A residence needs a new electric/water service connection.",
    requiredConditions: ["COND_RESIDENTIAL_USE", "COND_UTILITY_CONNECTION"],
    excludedConditions: [],
  },
  {
    id: "SCN_SUBDIVISION",
    label: "Property subdivision",
    description: "A parcel is being segregated or subdivided.",
    requiredConditions: ["COND_SUBDIVISION"],
    excludedConditions: [],
  },
  {
    id: "SCN_RESTAURANT_OPENING",
    label: "Restaurant opening",
    description: "A new restaurant opens and will prepare/serve food on site.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_RESTAURANT", "COND_FOOD_SERVICE"],
    excludedConditions: [],
  },
  {
    id: "SCN_DAYCARE_CONVERSION",
    label: "Daycare conversion",
    description: "An existing location is converted to a childcare/daycare establishment (change of use).",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_DAYCARE", "COND_USE_CHANGED"],
    excludedConditions: [],
  },
  {
    id: "SCN_PHARMACY_OPENING",
    label: "Pharmacy opening",
    description: "A new pharmacy opens.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_PHARMACY"],
    excludedConditions: [],
  },
  {
    id: "SCN_SOLAR_PROJECT",
    label: "Solar / renewable energy project",
    description: "A solar generation project, interconnected to the grid.",
    requiredConditions: ["COND_SOLAR", "COND_GRID_INTERCONNECTION"],
    excludedConditions: [],
  },
  {
    id: "SCN_MANUFACTURING_FACILITY",
    label: "Manufacturing facility",
    description: "A new manufacturing facility opens at a commercial site.",
    requiredConditions: ["COND_NEW_BUSINESS", "COND_MANUFACTURING", "COND_COMMERCIAL_USE"],
    excludedConditions: [],
  },
  {
    id: "SCN_MULTIPLE_CHANGES",
    label: "Business with multiple simultaneous changes",
    description: "An existing business simultaneously changes ownership, changes use, and remodels.",
    requiredConditions: [
      "COND_EXISTING_BUSINESS",
      "COND_OWNERSHIP_CHANGED",
      "COND_USE_CHANGED",
      "COND_REMODELING",
    ],
    excludedConditions: [],
  },
  {
    id: "SCN_OWNERSHIP_CHANGE_REMODEL",
    label: "Ownership change + remodel",
    description: "An existing business changes hands and remodels, keeping the same use.",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_OWNERSHIP_CHANGED", "COND_REMODELING"],
    excludedConditions: ["COND_USE_CHANGED", "COND_CONSTRUCTION_REQUIRED"],
  },
  {
    id: "SCN_CHANGE_OF_USE_CONSTRUCTION",
    label: "Change of use + construction",
    description: "An existing location changes use and undergoes construction work.",
    requiredConditions: ["COND_EXISTING_BUSINESS", "COND_USE_CHANGED", "COND_CONSTRUCTION_REQUIRED"],
    excludedConditions: [],
  },
  {
    id: "SCN_EXISTING_BIZ_STEADY",
    label: "Existing business, no changes",
    description:
      "An operating business with no ownership change, use change, construction, remodeling, " +
      "utility connection, subdivision, or renewal event.",
    requiredConditions: ["COND_EXISTING_BUSINESS"],
    excludedConditions: [
      "COND_OWNERSHIP_CHANGED",
      "COND_USE_CHANGED",
      "COND_CONSTRUCTION_REQUIRED",
      "COND_REMODELING",
      "COND_UTILITY_CONNECTION",
      "COND_SUBDIVISION",
      "COND_PERMIT_RENEWAL",
    ],
  },
  {
    id: "SCN_COMPLEX_GUAYNABO_RESTAURANT",
    label: "Bought existing Guaynabo restaurant; same use; kitchen remodel; ownership changed",
    description:
      "Complex: an existing restaurant in Guaynabo was purchased. It remains a restaurant (same use), " +
      "the kitchen is being remodeled, and ownership changed. Each applicable path must be detected and " +
      "explained separately: the ownership-transfer path and the remodel path.",
    requiredConditions: [
      "COND_EXISTING_BUSINESS",
      "COND_OWNERSHIP_CHANGED",
      "COND_SAME_USE",
      "COND_REMODELING",
      "COND_RESTAURANT",
      "COND_FOOD_SERVICE",
    ],
    excludedConditions: ["COND_USE_CHANGED", "COND_CONSTRUCTION_REQUIRED"],
  },
];

export const RP_VARIANTS: ProcessVariant[] = [
  {
    id: "VAR_FORMATION_CORP",
    label: "Corporate formation documents",
    processId: "PR_BUSINESS_FORMATION",
    selectorConditions: ["COND_NEW_BUSINESS", "COND_CORPORATION"],
    ruleIds: ["RULE_0001"],
    active: true,
    note: "Entity-type scoping beyond corporation (LLC, sole proprietorship) remains the rules engine's job.",
  },
  {
    id: "VAR_SURI_NEW_MERCHANT",
    label: "SURI merchant registration (new business)",
    processId: "PR_SURI_MERCHANT_REGISTRATION",
    selectorConditions: ["COND_NEW_BUSINESS"],
    ruleIds: ["RULE_0003"],
    active: true,
  },
  {
    id: "VAR_PATENTE_NEW",
    label: "Municipal patente (new business)",
    processId: "PR_MUNICIPAL_PATENTE",
    selectorConditions: ["COND_NEW_BUSINESS", "COND_COMMERCIAL_USE"],
    ruleIds: ["RULE_0004"],
    active: true,
  },
  {
    id: "VAR_PATENTE_EXISTING",
    label: "Municipal patente (existing business)",
    processId: "PR_MUNICIPAL_PATENTE",
    selectorConditions: ["COND_EXISTING_BUSINESS", "COND_COMMERCIAL_USE"],
    ruleIds: ["RULE_0004"],
    active: true,
  },
  {
    id: "VAR_PERMISO_UNICO_NEW_LOCATION",
    label: "Permiso Único — new business at an existing location",
    processId: "PR_OGPE_PERMISO_UNICO",
    selectorConditions: ["COND_NEW_BUSINESS", "COND_EXISTING_LOCATION"],
    ruleIds: ["RULE_0007"],
    active: true,
  },
  {
    id: "VAR_PERMISO_UNICO_RESTAURANT",
    label: "Permiso Único — restaurant",
    processId: "PR_OGPE_PERMISO_UNICO",
    selectorConditions: ["COND_RESTAURANT"],
    ruleIds: ["RULE_0049"],
    active: true,
  },
  {
    id: "VAR_PERMISO_UNICO_CHANGE_OF_USE",
    label: "Permiso Único — change of use",
    processId: "PR_OGPE_PERMISO_UNICO",
    selectorConditions: ["COND_USE_CHANGED"],
    ruleIds: ["RULE_0007"],
    active: true,
    note: "The KB models change-of-use under the general Permiso Único requirement; a distinct change-of-use process with its own rules is a regulatory-research gap.",
  },
  {
    id: "VAR_CONSTRUCTION_NEW",
    label: "OGPe construction permit — new construction",
    processId: "PR_OGPE_CONSTRUCTION_PERMIT",
    selectorConditions: ["COND_CONSTRUCTION_REQUIRED"],
    ruleIds: ["RULE_0643"],
    active: true,
  },
  {
    id: "VAR_CONSTRUCTION_RENOVATION",
    label: "OGPe construction permit — renovation / remodel",
    processId: "PR_OGPE_CONSTRUCTION_PERMIT",
    selectorConditions: ["COND_REMODELING"],
    ruleIds: ["RULE_0644"],
    active: true,
  },
  {
    id: "VAR_HEALTH_FOOD",
    label: "Department of Health food-establishment permit",
    processId: "PR_SALUD_FOOD_ESTABLISHMENT",
    selectorConditions: ["COND_FOOD_SERVICE"],
    ruleIds: ["RULE_0009"],
    active: true,
  },
  {
    id: "VAR_FIRE_FOOD",
    label: "Fire Department certification (food establishment)",
    processId: "PR_BOMBEROS_CERTIFICATION",
    selectorConditions: ["COND_FOOD_SERVICE"],
    ruleIds: ["RULE_0011"],
    active: true,
  },
  {
    id: "VAR_PHARMACY",
    label: "Pharmacy health permit",
    processId: "PR_SALUD_PHARMACY",
    selectorConditions: ["COND_PHARMACY"],
    ruleIds: ["RULE_0095"],
    active: true,
  },
  {
    id: "VAR_CHILDCARE",
    label: "Childcare establishment license",
    processId: "PR_FAMILIA_CHILDCARE",
    selectorConditions: ["COND_DAYCARE"],
    ruleIds: ["RULE_0194"],
    active: true,
  },
  {
    id: "VAR_SOLAR_INTERCONNECTION",
    label: "LUMA distributed-generation interconnection",
    processId: "PR_ENERGY_DG_INTERCONNECTION",
    selectorConditions: ["COND_SOLAR", "COND_GRID_INTERCONNECTION"],
    ruleIds: ["RULE_0610"],
    active: true,
  },
  {
    id: "VAR_SOLAR_INSTALLER",
    label: "Renewable installer certification",
    processId: "PR_ENERGY_INSTALLER_CERTIFICATION",
    selectorConditions: ["COND_SOLAR"],
    ruleIds: ["RULE_0605"],
    active: true,
    note: "Applies when the business is the solar installer; installer-vs-owner scoping is a refinement gap.",
  },
  {
    id: "VAR_OWNERSHIP_TRANSFER_OBLIGATIONS",
    label: "Ownership transfer — patente and SURI obligations",
    processId: "PR_OWNERSHIP_TRANSFER",
    selectorConditions: ["COND_OWNERSHIP_CHANGED", "COND_EXISTING_BUSINESS"],
    ruleIds: ["RULE_0004", "RULE_0003"],
    active: true,
    note: "Transfer (traspaso) mechanics are not yet modeled as distinct rules — regulatory-research gap. The underlying obligations (municipal patente, SURI merchant registration) transfer with the business.",
  },
];

export const REASONING_GRAPH: ReasoningGraph = {
  conditions: RP_CONDITIONS,
  scenarios: RP_SCENARIOS,
  variants: RP_VARIANTS,
};
